### ISSUE TITLE
API responses with status code 200 but error message in content

### ISSUE THREAD

**Issue by apriltuesday** [Ensembl/ensembl-biomart#144]
We're using the BioMart API in one of our pipelines and recently (within the last couple days) started getting responses with status code `200` but an error message in the content:
```
Query ERROR: caught BioMart::Exception::Database: Could not connect to mysql database ensembl_mart_104 .....
```
I've implemented a simple check to catch these on our end, but wanted to check whether this is intended behaviour.

[Here](https://github.com/apriltuesday/eva-opentargets/blob/master/consequence_prediction/repeat_expansion_variants/biomart.py) is where we make the request in our code, in case it's useful.

**Comment by marcoooo** [comment]
Hello @apriltuesday

For your future reference, technical questions like these should be directed to the Ensembl Helpdesk: https://www.ensembl.org/Help/Contact

If you have any further questions, please do contact the Ensembl Helpdesk with your original question and follow up questions and we'll do our best to help you from there.

Best wishes
Marc
